spring:
  application:
    name: spring-webflux-demo
  data:
    mongodb:
      uri: mongodb://localhost:27017/test
      database: test
  r2dbc:
    url: postgresql://postgres_container:5432/postgres?schema=postgres
    username: postgres
    password: postgres